# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Proto iOS' do
  pod 'Mixpanel'
end

target 'Proto Android' do

end

target 'Proto Mac' do

end

